services:
  Caddy:
    image: caddy:latest
    container_name: Caddy
    restart: unless-stopped
    hostname: caddy
    ports:
      - 443:443/tcp
      - 443:443/udp
    networks:
      Adguard:
      # Speed up connections from HA to cloud.mwdle.com by connecting directly via Caddy.
      Nextcloud:
        aliases:
          - cloud.mwdle.com
      CloudflareTunnel:
      Speedtest:
      APA:
      VPA:
      Frigate:
      # Home assistant connects to Music Assistant via Caddy instead of Docker network for HTTPS access/MA Music Art Proxy (mixed content in browser).
      # Home assistant connects to Frigate via Caddy instead of Docker network for HTTPS access, Frigate Authentication, and the ability to place HA and Frigate in different Docker networks, resulting in enhanced security.
      HomeAssistant:
        aliases:
          - music.mwdle.com
          - frigate.mwdle.com
      MusicAssistant:
    volumes:
      - ${DOCKER_VOLUMES}/Caddy/Caddyfile:/etc/caddy/Caddyfile
      - ${DOCKER_VOLUMES}/Caddy/data:/data
      - ${DOCKER_VOLUMES}/Caddy/config:/config

networks:
  Adguard:
    name: Adguard
    external: true
  Nextcloud:
    name: Nextcloud
    external: true
  CloudflareTunnel:
    name: CloudflareTunnel
    external: true
  Speedtest:
    name: Speedtest
    external: true
  VPA:
    name: VPA
    external: true
  APA:
    name: APA
    external: true
  Frigate:
    name: Frigate
    external: true
  HomeAssistant:
    name: HomeAssistant
    external: true
  MusicAssistant:
    name: MusicAssistant
    external: true