services:
  Caddy:
    image: caddy:latest
    container_name: Caddy
    restart: unless-stopped
    hostname: caddy
    ports:
      - 443:443/tcp
      - 443:443/udp
    networks:
      Adguard:
      Nextcloud:
      CloudflareTunnel:
      Speedtest:
      APA:
      VPA:
      Frigate:
      MusicAssistant:
      # Home assistant connects to Nextcloud via Caddy instead of Docker network for no external routing.
      # Home assistant connects to Music Assistant via Caddy instead of Docker network for HTTPS access/MA Music Art Proxy (avoids mixed content in browser).
      # Home assistant connects to Frigate via Caddy instead of Docker network for HTTPS access, Frigate Authentication, and the ability to segregate HA and Frigate Docker networks, resulting in enhanced security.
      HomeAssistant:
        aliases:
          - ${MA_HOSTNAME}
          - ${FRIGATE_HOSTNAME}
          - ${NEXTCLOUD_HOSTNAME}
    volumes:
      - ${DOCKER_VOLUMES}/Caddy/Caddyfile:/etc/caddy/Caddyfile
      - ${DOCKER_VOLUMES}/Caddy/data:/data
      - ${DOCKER_VOLUMES}/Caddy/config:/config

networks:
  Adguard:
    name: Adguard
    external: true
  Nextcloud:
    name: Nextcloud
    external: true
  CloudflareTunnel:
    name: CloudflareTunnel
    external: true
  Speedtest:
    name: Speedtest
    external: true
  VPA:
    name: VPA
    external: true
  APA:
    name: APA
    external: true
  Frigate:
    name: Frigate
    external: true
  HomeAssistant:
    name: HomeAssistant
    external: true
  MusicAssistant:
    name: MusicAssistant
    external: true